packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - prisma
  - unrs-resolver
  - '@hashibutogarasu/common'
  - '@thallesp/nestjs-better-auth'
  - 'protobufjs'
  - '@firebase/util'

pnpm:
  overrides:

catalogs:
  default:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest
    vite-plus: latest
