onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - prisma
  - unrs-resolver
  - '@karasu-lab/common'
