auth:
  trustedOrigins:
    - https://api.karasu256.com
    - https://sso.karasu256.com
    - https://www.karasu256.com
    - https://karasu256.com
    - https://id.karasu256.com
    - 'android:apk-key-hash:SEhtZj8Q-Fb0z9qGqUpYG3s1PbYvmiwZHYqmXe3tVHc'
  cookieDomain: '.karasu256.com'
  trustedProxies: []

passkey:
  rpId: 'karasu256.com'
  rpName: 'Karasu Lab'
  origins:
    - https://sso.karasu256.com
    - https://karasu256.com
    - https://www.karasu256.com
    - https://id.karasu256.com
    - 'android:apk-key-hash:SEhtZj8Q-Fb0z9qGqUpYG3s1PbYvmiwZHYqmXe3tVHc'

bluesky:
  redirectUri: 'net.karasuniki.karasulab:/oauth/callback'

rateLimit:
  enabled: true
  window: 60
  max: 100
