auth:
  trustedOrigins:
    - https://api.karasu256.com
    - https://sso.karasu256.com
    - https://www.karasu256.com
    - https://karasu256.com
    - https://id.karasu256.com
    - 'android:apk-key-hash:SEhtZj8Q-Fb0z9qGqUpYG3s1PbYvmiwZHYqmXe3tVHc'
  cookieDomain: '.karasu256.com'
  trustedProxies: []

passkey:
  rpId: 'karasu256.com'
  rpName: 'Karasu Lab'
  origins:
    - https://sso.karasu256.com
    - https://karasu256.com
    - https://www.karasu256.com
    - https://id.karasu256.com
    - 'android:apk-key-hash:SEhtZj8Q-Fb0z9qGqUpYG3s1PbYvmiwZHYqmXe3tVHc'

android:
  packageName: 'net.karasuniki.karasulab'
  sha256CertFingerprints:
    - '48:48:6d:66:3f:10:f8:56:f4:cf:da:86:a9:4a:58:1b:7b:35:3d:b6:2f:9a:2c:19:1d:8a:a6:5d:ed:ed:54:77'

bluesky:
  redirectUris:
    - 'com.karasu256.id://oauth/'
    - 'com.karasu256.id://oauth'
    - 'https://karasu256.com/api/auth/callback/bluesky'

rateLimit:
  enabled: true
  window: 60
  max: 100
