import type { IObjectStorage } from '../../src/storage/object-storage.interface.js';

interface StoredObject {
  body: Buffer;
  contentType?: string;
}

/** In-memory implementation of IObjectStorage for use in unit/integration tests. */
export class NullObjectStorageService implements IObjectStorage {
  private readonly store = new Map<string, StoredObject>();

  /**
   * Base URL prefix used in stub presigned upload URLs.
   * Exposed so tests can construct or validate URLs.
   */
  static readonly UPLOAD_BASE = 'https://test-stub/upload/';

  getPublicUrl(key: string): Promise<string> {
    return Promise.resolve(`https://test-stub/public/${key}`);
  }

  getPresignedUrl(key: string, expiresIn?: number): Promise<string> {
    let url = `https://test-stub/${key}`;
    if (expiresIn) {
      url += `?X-Amz-Expires=${expiresIn}`;
    }
    return Promise.resolve(url);
  }

  /**
   * Returns a stub presigned upload URL for the given key and content type.
   * The URL encodes the object key in the path and the content type as a query
   * parameter so that {@link simulateUploadViaPresignedUrl} can reconstruct them.
   * @param key         Object key
   * @param contentType MIME type of the object to be uploaded
   * @param expiresIn   Expiry duration in seconds
   */
  getPresignedUploadUrl(
    key: string,
    contentType: string,
    expiresIn?: number,
  ): Promise<string> {
    let url = `${NullObjectStorageService.UPLOAD_BASE}${key}?content-type=${encodeURIComponent(contentType)}`;
    if (expiresIn) {
      url += `&X-Amz-Expires=${expiresIn}`;
    }
    return Promise.resolve(url);
  }

  /**
   * Simulates a client PUT request to a presigned upload URL.
   *
   * In production the client would issue an HTTP PUT directly to the R2 endpoint.
   * In tests this method extracts the object key and content type from the stub
   * URL generated by {@link getPresignedUploadUrl} and stores the object in the
   * in-memory store, making it visible to {@link getObjectMetadata}.
   *
   * Throws if the URL does not match the expected stub format.
   * @param presignedUrl URL returned by getPresignedUploadUrl
   * @param body         File contents to store
   */
  simulateUploadViaPresignedUrl(presignedUrl: string, body: Buffer): Promise<void> {
    if (!presignedUrl.startsWith(NullObjectStorageService.UPLOAD_BASE)) {
      return Promise.reject(
        new Error(`Invalid presigned upload URL: ${presignedUrl}`),
      );
    }

    const withoutBase = presignedUrl.slice(NullObjectStorageService.UPLOAD_BASE.length);
    const queryStart = withoutBase.indexOf('?');
    const key = queryStart === -1 ? withoutBase : withoutBase.slice(0, queryStart);
    const query = queryStart === -1 ? '' : withoutBase.slice(queryStart + 1);

    const params = new URLSearchParams(query);
    const contentType = params.get('content-type') ?? 'application/octet-stream';

    this.store.set(key, { body, contentType });
    return Promise.resolve();
  }

  /**
   * Returns metadata for an object that was previously stored via putObject or
   * simulateUploadViaPresignedUrl.
   * Returns null when no object is found for the given key.
   * @param key Object key
   */
  getObjectMetadata(
    key: string,
  ): Promise<{ contentType: string; size: number } | null> {
    const obj = this.store.get(key);
    if (!obj) return Promise.resolve(null);
    return Promise.resolve({
      contentType: obj.contentType ?? 'application/octet-stream',
      size: obj.body.length,
    });
  }

  putObject(key: string, body: Buffer | Uint8Array, contentType?: string): Promise<void> {
    this.store.set(key, {
      body: Buffer.isBuffer(body) ? body : Buffer.from(body),
      contentType,
    });
    return Promise.resolve();
  }

  getContentType(key: string): Promise<string | undefined> {
    return Promise.resolve(this.store.get(key)?.contentType);
  }

  getObject(key: string): Promise<Buffer | null> {
    return Promise.resolve(this.store.get(key)?.body ?? null);
  }

  deleteObject(key: string): Promise<void> {
    this.store.delete(key);
    return Promise.resolve();
  }

  listObjects(prefix?: string): Promise<string[]> {
    const keys = Array.from(this.store.keys());
    if (!prefix) {
      return Promise.resolve(keys);
    }
    return Promise.resolve(keys.filter((key) => key.startsWith(prefix)));
  }
}
